name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this solve? What's the motivation?
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
        Current workflow requires...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work? Be specific.
      placeholder: |
        Add a new flag `--format json` that outputs results in JSON format.
        
        Example:
        ```bash
        $ tool --format json
        { "result": "data" }
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you think about?
      placeholder: |
        - Option A: ...
        - Option B: ...
        - Current workaround: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, links, etc.
      placeholder: |
        - Similar feature in other tools: ...
        - Related issues: ...
        - Code examples: ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help test this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: This feature aligns with the tool's purpose
          required: true
